quarkus.datasource.db-kind=postgresql
quarkus.datasource.username={POSTGRESQL_USERNAME}
quarkus.datasource.password={POSTGRESQL_PASSWORD}

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus-social
quarkus.datasource.jdbc.max-size=16